# Generated by Django 3.2.5 on 2021-07-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmembers',
            old_name='Atcoder_account',
            new_name='atcoderAccount',
        ),
        migrations.RenameField(
            model_name='clubmembers',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='clubmembers',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='clubmembers',
            old_name='Github_URL',
            new_name='githubAccount',
        ),
    ]
