# Generated by Django 3.2.5 on 2021-07-14 01:14

from django.db import migrations
from introduction.models import ClubMembers
import csv
def load_initial_data(apps, schema_editor):

    with open('member_info.csv',  encoding= "utf8") as csv_file:
        reader = csv.reader(csv_file)
        next(reader)
        for row in reader:
             _, created = ClubMembers.objects.get_or_create(
                name = row[1],
                year = row[2],
                course = row[3],
                description = row[6],
                githubAccount = row[4],
                atcoderAccount = row[5]
                )
class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_auto_20210713_2240'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]